/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class CreateTuitionForm extends javax.swing.JPanel {
    double totalOfFees;
    /**
     * Creates new form CreateTuitionGUI
     */
    public CreateTuitionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        yearFromJcbx = new javax.swing.JComboBox<>();
        yearToJcbx = new javax.swing.JComboBox<>();
        gradeLevelJcbx = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        basicFeeAmountJtf = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        clearTuitionJbtn = new javax.swing.JButton();
        addTuitionFeeJbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        itemNameMiscellaneousJtf = new javax.swing.JTextField();
        amountMiscellaneousJtf = new javax.swing.JTextField();
        clearMiscellaneousFieldsJbtn = new javax.swing.JButton();
        addMiscellaneousJbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        itemNameOthersJtf = new javax.swing.JTextField();
        amountOthersJtf = new javax.swing.JTextField();
        clearOthersFeesJbtn = new javax.swing.JButton();
        addOthersJbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        feesJtbl = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        cancelJbtn = new javax.swing.JButton();
        createJbtn = new javax.swing.JButton();
        removeSelectedJbtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        totalJlbl = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feesDescriptionJta = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        yearFromJcbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearFromJcbxItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(yearFromJcbx, gridBagConstraints);

        yearToJcbx.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(yearToJcbx, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(gradeLevelJcbx, gridBagConstraints);

        jLabel4.setText("School Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel4, gridBagConstraints);

        jLabel5.setText("to");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Grade Level");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Amount Php");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(basicFeeAmountJtf, gridBagConstraints);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        clearTuitionJbtn.setText("Clear");
        clearTuitionJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTuitionJbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel8.add(clearTuitionJbtn, gridBagConstraints);

        addTuitionFeeJbtn.setText("Add");
        addTuitionFeeJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTuitionFeeJbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel8.add(addTuitionFeeJbtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jPanel8, gridBagConstraints);

        jLabel12.setText("Basic Fee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(itemNameMiscellaneousJtf, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(amountMiscellaneousJtf, gridBagConstraints);

        clearMiscellaneousFieldsJbtn.setText("Clear");
        clearMiscellaneousFieldsJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMiscellaneousFieldsJbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(clearMiscellaneousFieldsJbtn, gridBagConstraints);

        addMiscellaneousJbtn.setText("Add");
        addMiscellaneousJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMiscellaneousJbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(addMiscellaneousJbtn, gridBagConstraints);

        jLabel1.setText("Item Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Amount Php");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Miscellaneous Fee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(itemNameOthersJtf, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(amountOthersJtf, gridBagConstraints);

        clearOthersFeesJbtn.setText("Clear");
        clearOthersFeesJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearOthersFeesJbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(clearOthersFeesJbtn, gridBagConstraints);

        addOthersJbtn.setText("Add");
        addOthersJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOthersJbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(addOthersJbtn, gridBagConstraints);

        jLabel9.setText("Other Fee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Item Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Amount Php");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(jLabel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        feesJtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Amount", "Type", "Grade Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        feesJtbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(feesJtbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jScrollPane2, gridBagConstraints);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        cancelJbtn.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel7.add(cancelJbtn, gridBagConstraints);

        createJbtn.setText("Create");
        createJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel7.add(createJbtn, gridBagConstraints);

        removeSelectedJbtn.setText("Remove Selected");
        removeSelectedJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSelectedJbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel7.add(removeSelectedJbtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jPanel7, gridBagConstraints);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Total");
        jPanel9.add(jLabel13);

        totalJlbl.setText("Amount");
        jPanel9.add(totalJlbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jPanel9, gridBagConstraints);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel14.setText("Description of Fees");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel10.add(jLabel14, gridBagConstraints);

        feesDescriptionJta.setColumns(20);
        feesDescriptionJta.setRows(5);
        jScrollPane1.setViewportView(feesDescriptionJta);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel10.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jPanel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jPanel6, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void yearFromJcbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearFromJcbxItemStateChanged
        if(yearFromJcbx.getSelectedIndex() > -1){
            int selected = yearFromJcbx.getSelectedIndex();
            yearToJcbx.setSelectedIndex(selected);
        }
    }//GEN-LAST:event_yearFromJcbxItemStateChanged

    private void clearTuitionJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTuitionJbtnActionPerformed
        basicFeeAmountJtf.setText("");
    }//GEN-LAST:event_clearTuitionJbtnActionPerformed

    private void addTuitionFeeJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTuitionFeeJbtnActionPerformed
        if (basicFeeAmountJtf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out Amount fee field");
        } else {
            DefaultTableModel myModel = (DefaultTableModel) feesJtbl.getModel();
            double myBasicFeeAmount = Double.parseDouble(basicFeeAmountJtf.getText());
            DecimalFormat myDf = new DecimalFormat("#,###.00");
            myModel.addRow(new Object[]{"Basic Fee", '\u20B1' + " " + myDf.format(myBasicFeeAmount), "Tuition"});

            double totalOfTuition = 0;
            double doubleAmount;

            totalOfFees = 0;
            for (int x = 0; x < feesJtbl.getRowCount(); x++) {
                String valueWithPesosSign = ((String) myModel.getValueAt(x, 1));
                String stringAmount = valueWithPesosSign.replaceAll("\\P{Print}", "").replaceAll(",","");
                doubleAmount = Double.valueOf(stringAmount);
                totalOfTuition += doubleAmount;
            }
            totalOfFees = totalOfTuition;
            totalJlbl.setText(""+'\u20B1' +" "+ myDf.format(totalOfFees) );
            //JOptionPane.showMessageDialog(null,"Total: "+ totalOfFees);
            basicFeeAmountJtf.setText("");
        }
    }//GEN-LAST:event_addTuitionFeeJbtnActionPerformed

    private void clearMiscellaneousFieldsJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMiscellaneousFieldsJbtnActionPerformed
        itemNameMiscellaneousJtf.setText("");
        amountMiscellaneousJtf.setText("");
    }//GEN-LAST:event_clearMiscellaneousFieldsJbtnActionPerformed

    private void addMiscellaneousJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMiscellaneousJbtnActionPerformed
        if ((itemNameMiscellaneousJtf.getText().isEmpty()) || (amountMiscellaneousJtf.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Please fill out both fields");
        } else {
            DefaultTableModel myModel = (DefaultTableModel) feesJtbl.getModel();
            String myMiscellaneousItemName = itemNameMiscellaneousJtf.getText();
            double myMiscellaneousAmount = Double.parseDouble(amountMiscellaneousJtf.getText());
            DecimalFormat myDf = new DecimalFormat("#,###.00");
            myModel.addRow(new Object[]{myMiscellaneousItemName, '\u20B1' + " " + myDf.format(myMiscellaneousAmount), "Miscellaneous"});

            double totalOfTuition = 0;
            double doubleAmount;

            totalOfFees = 0;
            for (int x = 0; x < feesJtbl.getRowCount(); x++) {
                String valueWithPesosSign = ((String) myModel.getValueAt(x, 1));
                String stringAmount = valueWithPesosSign.replaceAll("\\P{Print}", "").replaceAll(",","");
                //JOptionPane.showMessageDialog(null, stringAmount);
                doubleAmount = Double.parseDouble(stringAmount);
                totalOfTuition += doubleAmount;
            }
            totalOfFees = totalOfTuition;
            totalJlbl.setText(""+'\u20B1' +" "+ myDf.format(totalOfFees) );
            //JOptionPane.showMessageDialog(null,"Total: "+ totalOfFees);

            itemNameMiscellaneousJtf.setText("");
            amountMiscellaneousJtf.setText("");
        }
    }//GEN-LAST:event_addMiscellaneousJbtnActionPerformed

    private void clearOthersFeesJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearOthersFeesJbtnActionPerformed
        itemNameOthersJtf.setText("");
        amountOthersJtf.setText("");
    }//GEN-LAST:event_clearOthersFeesJbtnActionPerformed

    private void addOthersJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOthersJbtnActionPerformed
        if ((itemNameOthersJtf.getText().isEmpty()) || (amountOthersJtf.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Please fill out both fields");
        } else {
            DefaultTableModel myModel = (DefaultTableModel) feesJtbl.getModel();
            String myOtherFeeAmount = itemNameOthersJtf.getText();
            double myOtherAmount = Double.parseDouble(amountOthersJtf.getText());
            DecimalFormat myDf = new DecimalFormat("#,###.00");
            myModel.addRow(new Object[]{myOtherFeeAmount, '\u20B1' + " " + myDf.format(myOtherAmount), "Others"});

            double totalOfTuition = 0;
            double doubleAmount;

            totalOfFees = 0;
            for (int x = 0; x < feesJtbl.getRowCount(); x++) {
                String valueWithPesosSign = ((String) myModel.getValueAt(x, 1));
                String stringAmount = valueWithPesosSign.replaceAll("\\P{Print}", "").replaceAll(",","");
                //JOptionPane.showMessageDialog(null, stringAmount);
                doubleAmount = Double.parseDouble(stringAmount);
                totalOfTuition += doubleAmount;
            }
            totalOfFees = totalOfTuition;
            totalJlbl.setText(""+'\u20B1' +" "+ myDf.format(totalOfFees) );
            //JOptionPane.showMessageDialog(null,"Total: "+ totalOfFees);

            itemNameOthersJtf.setText("");
            amountOthersJtf.setText("");
        }
    }//GEN-LAST:event_addOthersJbtnActionPerformed

    private void createJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJbtnActionPerformed

        int error = 0;
        int mySyYearFrom = 0, mySyYearTo = 0;
        double doubleValueOfAmount;
        String myFeeType, myAmount, myFeeName, myFeeDescription, myGradeLevel = null;

        for (int i = 0; i < feesJtbl.getRowCount(); i++) {
            myFeeType           = (String) feesJtbl.getValueAt(i, 2);
            myAmount            = (String) feesJtbl.getValueAt(i, 1);
            myFeeName           = (String) feesJtbl.getValueAt(i, 0);
            myFeeDescription    = feesDescriptionJta.getText();
            myAmount            = myAmount.replaceAll("\\P{Print}", "").replaceAll(",", "");
            myGradeLevel        = gradeLevelJcbx.getSelectedItem().toString();
            mySyYearFrom        = Integer.parseInt(yearFromJcbx.getSelectedItem().toString());
            mySyYearTo          = Integer.parseInt(yearToJcbx.getSelectedItem().toString().trim());
            doubleValueOfAmount = Double.parseDouble(myAmount);

            
        }// end of for loop

        if (error == 0) {
            JOptionPane.showMessageDialog(null, "Sucessfully added fees for " + myGradeLevel + " SY: " + mySyYearFrom + "-" + mySyYearTo);
        }
    }//GEN-LAST:event_createJbtnActionPerformed

    private void removeSelectedJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSelectedJbtnActionPerformed

        if(feesJtbl.getSelectedRowCount() > 0){
            int mySelectedRow = feesJtbl.getSelectedRow();
            String firstColumnValue = (String) feesJtbl.getValueAt(mySelectedRow, 0);
            String secondColumnValue = (String) feesJtbl.getValueAt(mySelectedRow, 1);
            String thirdColumnValue = (String) feesJtbl.getValueAt(mySelectedRow, 2);

            int choice = JOptionPane.showConfirmDialog(null, "Remove?\n " + firstColumnValue + "\n" + secondColumnValue + "\n" + thirdColumnValue, "Remove", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                DefaultTableModel myModel = (DefaultTableModel) feesJtbl.getModel();
                myModel.removeRow(mySelectedRow);
                secondColumnValue = secondColumnValue.replaceAll("\\P{Print}", "").replaceAll(",","");
                totalOfFees = (totalOfFees - Double.parseDouble(secondColumnValue) );
                DecimalFormat myDf = new DecimalFormat("#,###.00");
                totalJlbl.setText(""+'\u20B1' +" "+ myDf.format(totalOfFees) );
            }
        }else if(feesJtbl.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null,"Please select the row you want to delete");
        }
    }//GEN-LAST:event_removeSelectedJbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMiscellaneousJbtn;
    private javax.swing.JButton addOthersJbtn;
    private javax.swing.JButton addTuitionFeeJbtn;
    private javax.swing.JTextField amountMiscellaneousJtf;
    private javax.swing.JTextField amountOthersJtf;
    private javax.swing.JTextField basicFeeAmountJtf;
    private javax.swing.JButton cancelJbtn;
    private javax.swing.JButton clearMiscellaneousFieldsJbtn;
    private javax.swing.JButton clearOthersFeesJbtn;
    private javax.swing.JButton clearTuitionJbtn;
    private javax.swing.JButton createJbtn;
    private javax.swing.JTextArea feesDescriptionJta;
    private javax.swing.JTable feesJtbl;
    private javax.swing.JComboBox<String> gradeLevelJcbx;
    private javax.swing.JTextField itemNameMiscellaneousJtf;
    private javax.swing.JTextField itemNameOthersJtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeSelectedJbtn;
    private javax.swing.JLabel totalJlbl;
    private javax.swing.JComboBox<String> yearFromJcbx;
    private javax.swing.JComboBox<String> yearToJcbx;
    // End of variables declaration//GEN-END:variables
}
