/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import model.DatabaseConnectionProperty;
import service.DBConfigurationCreator;

/**
 *
 * @author John Ferdinand Antonio
 */
public class DBConnectionForm extends javax.swing.JDialog {

    /**
     * Creates new form DatabaseConnectionSettings
     */
    public DBConnectionForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpnlConnectionConfiguration = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfIPAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfPortNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDatabaseName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfConnectionUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfConnectionPassword = new javax.swing.JTextField();
        jbtnSaveSettings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jpnlConnectionConfiguration.setBorder(javax.swing.BorderFactory.createTitledBorder("Connection Configuration"));
        jpnlConnectionConfiguration.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("IP Address :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jLabel1, gridBagConstraints);

        jtfIPAddress.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jtfIPAddress, gridBagConstraints);

        jLabel2.setText("Port :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jLabel2, gridBagConstraints);

        jtfPortNumber.setColumns(3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jtfPortNumber, gridBagConstraints);

        jLabel3.setText("(Schema) Database Name: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jLabel3, gridBagConstraints);

        jtfDatabaseName.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jtfDatabaseName, gridBagConstraints);

        jLabel4.setText("Connection Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jLabel4, gridBagConstraints);

        jtfConnectionUsername.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jtfConnectionUsername, gridBagConstraints);

        jLabel5.setText("Connection Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jLabel5, gridBagConstraints);

        jtfConnectionPassword.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlConnectionConfiguration.add(jtfConnectionPassword, gridBagConstraints);

        getContentPane().add(jpnlConnectionConfiguration, new java.awt.GridBagConstraints());

        jbtnSaveSettings.setText("Save");
        jbtnSaveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveSettingsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jbtnSaveSettings, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveSettingsActionPerformed
        DatabaseConnectionProperty dbConProp = new DatabaseConnectionProperty();
        dbConProp.setDatabaseName(jtfDatabaseName.getText().trim());
        dbConProp.setIpAddress(jtfIPAddress.getText().trim());
        dbConProp.setUserName(jtfConnectionUsername.getText().trim());
        dbConProp.setPassword(jtfConnectionPassword.getText().trim());
        dbConProp.setPortNumber(jtfPortNumber.getText().trim());
        
        DBConfigurationCreator dbcc = new DBConfigurationCreator(dbConProp);
        boolean isCreated = dbcc.create();
        if(isCreated){
            JOptionPane.showMessageDialog(null,"Configuration file created.");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Error creating configuration file.");
        }
    }//GEN-LAST:event_jbtnSaveSettingsActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        
    }//GEN-LAST:event_jLabel1MouseEntered

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnSaveSettings;
    private javax.swing.JPanel jpnlConnectionConfiguration;
    private javax.swing.JTextField jtfConnectionPassword;
    private javax.swing.JTextField jtfConnectionUsername;
    private javax.swing.JTextField jtfDatabaseName;
    private javax.swing.JTextField jtfIPAddress;
    private javax.swing.JTextField jtfPortNumber;
    // End of variables declaration//GEN-END:variables
}
