package view.subject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import component_model_loader.GradeLevelML;
import daoimpl.GradeLevelDaoImpl;
import daoimpl.SubjectDaoImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.GradeLevel;
import model.Subject;
import validation.SubjectValidation;
import static view.subject.SubjectManagementContainer.getTblSubjectList;


/**
 *
 * @author francisunoxx
 */
public class UpdateSubject extends javax.swing.JFrame {

    GradeLevelML gl = new GradeLevelML();
    
    Subject subject = new Subject();
    GradeLevel gradeLevel = new GradeLevel();
    
    GradeLevelDaoImpl gldi = new GradeLevelDaoImpl();
    SubjectDaoImpl sdi = new SubjectDaoImpl();
    public UpdateSubject() 
    {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        pack();
        
        jcmbGradeLevel.setModel(gl.getAllGradeLevels());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jtfSubjectName = new javax.swing.JTextField();
        jtfSubjectCode = new javax.swing.JTextField();
        jcmbGradeLevel = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtfDescription = new javax.swing.JTextArea();
        jlblSubjectDescription = new javax.swing.JLabel();
        jlblGradeLevel = new javax.swing.JLabel();
        jlblSubjectCode = new javax.swing.JLabel();
        jlblSubjectName = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiApply = new javax.swing.JMenuItem();
        jmiClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Subject"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jtfSubjectName.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jtfSubjectName, gridBagConstraints);

        jtfSubjectCode.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jtfSubjectCode, gridBagConstraints);

        jcmbGradeLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbGradeLevelItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jcmbGradeLevel, gridBagConstraints);

        jtfDescription.setColumns(20);
        jtfDescription.setRows(5);
        jScrollPane2.setViewportView(jtfDescription);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 10);
        jPanel3.add(jScrollPane2, gridBagConstraints);

        jlblSubjectDescription.setText("Subject Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 10);
        jPanel3.add(jlblSubjectDescription, gridBagConstraints);

        jlblGradeLevel.setText("Grade Level:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 10);
        jPanel3.add(jlblGradeLevel, gridBagConstraints);

        jlblSubjectCode.setText("Subject Code:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 10);
        jPanel3.add(jlblSubjectCode, gridBagConstraints);

        jlblSubjectName.setText("Subject Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 10);
        jPanel3.add(jlblSubjectName, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Subject Details", jPanel2);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Actions");

        jmiApply.setText("Apply");
        jmiApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiApplyActionPerformed(evt);
            }
        });
        jMenu1.add(jmiApply);

        jmiClose.setText("Close");
        jmiClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCloseActionPerformed(evt);
            }
        });
        jMenu1.add(jmiClose);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbGradeLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbGradeLevelItemStateChanged
        gradeLevel.setLevel((Integer) jcmbGradeLevel.getSelectedItem());
    }//GEN-LAST:event_jcmbGradeLevelItemStateChanged

    private void jmiCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jmiCloseActionPerformed

    private void jmiApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiApplyActionPerformed
        //Add all input to list
        List <Object> list = new ArrayList();
        list.add(jtfSubjectName.getText());
        list.add(jtfSubjectCode.getText());
        list.add(jcmbGradeLevel.getSelectedItem());
        list.add(jtfDescription.getText());
        
        /***********************************************************************/
        
        //Setter call from Subject & while getting the id from table
        subject.setSubjectId((int) getTblSubjectList().getValueAt(getTblSubjectList().getSelectedRow(), 0));
        
        //Retain only same element between two list
        list.retainAll(new SubjectValidation().checkSubjectChanges(subject));
        
        //If nothing changes
        if(list.size() == 4)
        {
            JOptionPane.showMessageDialog(null, "No changes detected");
        }
        //If anything changes
        else
        {
            //Setter call from Subject
            subject.setSubjectCode(jtfSubjectCode.getText());
            
            //If subject exist
//            if(sdi.checkSubjectExists(subject) == true)
//            {
//                JOptionPane.showMessageDialog(null, "Subject code "+jtfSubjectCode.getText() + " already exist");
            
                //Validation
//                jtfSubjectCode.setName("tfSubjectCode");
//                jtfSubjectCode.setBackground(Color.pink);
//                jtfSubjectCode.setInputVerifier(new Validation());
//            }
            //If doesn't exist
//            else
//            {
                //Setter call from Subject & while getting the id from table
                subject.setSubjectId((int) getTblSubjectList().getValueAt(getTblSubjectList().getSelectedRow(), 0));
        
                subject.setSubjectTitle(jtfSubjectName.getText());
        
                subject.setSubjectDescription(jtfDescription.getText());
        
                //Setter call from GradeLevel & while getting the id from jcmbGradeLevel
                gradeLevel.setId(gldi.getId(gradeLevel));
        
                if(sdi.updateCreatedSubjectById(subject, gradeLevel) == true)
                {
                    JOptionPane.showMessageDialog(null, "Successfully updating subject "+jtfSubjectName.getText());
                }
//            }
        }
        
        


    }//GEN-LAST:event_jmiApplyActionPerformed
    
    
    public JTextField getTfSubjectName()
    {
        return jtfSubjectName;
    }
    
    public static JTextField getTfSubjectCode()
    {
        return jtfSubjectCode;
    }
    
    public JComboBox getCbGradeLevel()
    {
        return jcmbGradeLevel;
    }
    
    public JTextArea getTaSubjectDescription()
    {
        return jtfDescription;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcmbGradeLevel;
    private javax.swing.JLabel jlblGradeLevel;
    private javax.swing.JLabel jlblSubjectCode;
    private javax.swing.JLabel jlblSubjectDescription;
    private javax.swing.JLabel jlblSubjectName;
    private javax.swing.JMenuItem jmiApply;
    private javax.swing.JMenuItem jmiClose;
    private javax.swing.JTextArea jtfDescription;
    private static javax.swing.JTextField jtfSubjectCode;
    private javax.swing.JTextField jtfSubjectName;
    // End of variables declaration//GEN-END:variables
}
