/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.UIManager;
import daoimpl.PaymentDaoImpl_OLD;
import daoimpl.SchoolYearDaoImpl;
import component_model_loader.JSpinnerGUIUtil;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Acer
 */
public class SetPaymentScheduleGUI extends javax.swing.JPanel {

    /**
     * Creates new form SetPaymentScheduleGUI
     */
    public SetPaymentScheduleGUI() {
        initComponents();
        UIManager.put("TextField.disabledBackground", new Color(255, 255, 255));
        UIManager.put("TextField.inactiveForeground", Color.BLACK);
        UIManager.put("ComboBox.disabledBackground", new Color(212, 212, 210));
        UIManager.put("ComboBox.disabledForeground", Color.BLACK);
        paymentTermJcbx.setModel(PaymentDaoImpl_OLD.Term.getAll());
        paymentTermJcbx.setSelectedIndex(-1);
        setAllJSpinnerEditorToDate();
        
        SchoolYearDaoImpl sy = new SchoolYearDaoImpl();
//        yearFromJcbx.setModel(sy.getAllStart());
//        yearToJcbx.setModel(sy.getAllEnd());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paymentTermJcbx = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        yearFromJcbx = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        yearToJcbx = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        quarterlyDownPaymentJSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        quarterlySecondPaymentJSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        quarterlyThirdPaymentJSpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        quarterlyFourthPaymentJSpinner = new javax.swing.JSpinner();
        saveQuarterlyScheduleJbtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        semestralDownPaymentJSpinner = new javax.swing.JSpinner();
        semestralSecondPaymentJSpinner = new javax.swing.JSpinner();
        saveSemestralScheduleJbtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Schedule"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Payment Term");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel1, gridBagConstraints);

        paymentTermJcbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paymentTermJcbxItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(paymentTermJcbx, gridBagConstraints);

        jLabel2.setText("School Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel2, gridBagConstraints);

        yearFromJcbx.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(yearFromJcbx, gridBagConstraints);

        jLabel3.setText("to");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel3, gridBagConstraints);

        yearToJcbx.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(yearToJcbx, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 350));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Quarterly"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("DownPayment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel4, gridBagConstraints);

        quarterlyDownPaymentJSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quarterlyDownPaymentJSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        quarterlyDownPaymentJSpinner.setEnabled(false);
        quarterlyDownPaymentJSpinner.setPreferredSize(new java.awt.Dimension(163, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(quarterlyDownPaymentJSpinner, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("2nd Payment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel6, gridBagConstraints);

        quarterlySecondPaymentJSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quarterlySecondPaymentJSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        quarterlySecondPaymentJSpinner.setEnabled(false);
        quarterlySecondPaymentJSpinner.setPreferredSize(new java.awt.Dimension(163, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(quarterlySecondPaymentJSpinner, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("3rd Payment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel7, gridBagConstraints);

        quarterlyThirdPaymentJSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quarterlyThirdPaymentJSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        quarterlyThirdPaymentJSpinner.setEnabled(false);
        quarterlyThirdPaymentJSpinner.setPreferredSize(new java.awt.Dimension(163, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(quarterlyThirdPaymentJSpinner, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("4th Payment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel8, gridBagConstraints);

        quarterlyFourthPaymentJSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quarterlyFourthPaymentJSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        quarterlyFourthPaymentJSpinner.setEnabled(false);
        quarterlyFourthPaymentJSpinner.setPreferredSize(new java.awt.Dimension(163, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(quarterlyFourthPaymentJSpinner, gridBagConstraints);

        saveQuarterlyScheduleJbtn.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(saveQuarterlyScheduleJbtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Semestral"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("DownPayment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("2nd Payment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(jLabel10, gridBagConstraints);

        semestralDownPaymentJSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        semestralDownPaymentJSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        semestralDownPaymentJSpinner.setEnabled(false);
        semestralDownPaymentJSpinner.setPreferredSize(new java.awt.Dimension(163, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(semestralDownPaymentJSpinner, gridBagConstraints);

        semestralSecondPaymentJSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        semestralSecondPaymentJSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        semestralSecondPaymentJSpinner.setEnabled(false);
        semestralSecondPaymentJSpinner.setPreferredSize(new java.awt.Dimension(163, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(semestralSecondPaymentJSpinner, gridBagConstraints);

        saveSemestralScheduleJbtn.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(saveSemestralScheduleJbtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jPanel3, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void paymentTermJcbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paymentTermJcbxItemStateChanged
        // TODO add your handling code here:
        if(paymentTermJcbx.getSelectedIndex() > -1){
            String selectedPaymentTerm = paymentTermJcbx.getSelectedItem().toString().trim();
            if(selectedPaymentTerm.equals("Quarterly") ){
                quarterlyDownPaymentJSpinner.setEnabled(true);
                quarterlySecondPaymentJSpinner.setEnabled(true);
                quarterlyThirdPaymentJSpinner.setEnabled(true);
                quarterlyFourthPaymentJSpinner.setEnabled(true);
            }else if(selectedPaymentTerm.equals("Semestral")){
                semestralDownPaymentJSpinner.setEnabled(true);
                semestralSecondPaymentJSpinner.setEnabled(true);
            }
        }
    }//GEN-LAST:event_paymentTermJcbxItemStateChanged

    private void setAllJSpinnerEditorToDate() {
        JSpinnerGUIUtil.setEditorInDateFormat(quarterlyDownPaymentJSpinner);
        JSpinnerGUIUtil.setEditorInDateFormat(quarterlySecondPaymentJSpinner);
        JSpinnerGUIUtil.setEditorInDateFormat(quarterlyThirdPaymentJSpinner);
        JSpinnerGUIUtil.setEditorInDateFormat(quarterlyFourthPaymentJSpinner);
        
        JSpinnerGUIUtil.setEditorInDateFormat(semestralDownPaymentJSpinner);
        JSpinnerGUIUtil.setEditorInDateFormat(semestralSecondPaymentJSpinner);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> paymentTermJcbx;
    private javax.swing.JSpinner quarterlyDownPaymentJSpinner;
    private javax.swing.JSpinner quarterlyFourthPaymentJSpinner;
    private javax.swing.JSpinner quarterlySecondPaymentJSpinner;
    private javax.swing.JSpinner quarterlyThirdPaymentJSpinner;
    private javax.swing.JButton saveQuarterlyScheduleJbtn;
    private javax.swing.JButton saveSemestralScheduleJbtn;
    private javax.swing.JSpinner semestralDownPaymentJSpinner;
    private javax.swing.JSpinner semestralSecondPaymentJSpinner;
    private javax.swing.JComboBox<String> yearFromJcbx;
    private javax.swing.JComboBox<String> yearToJcbx;
    // End of variables declaration//GEN-END:variables
}
