/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import component_model_loader.CurriculumML;
import component_model_loader.GradeLevelML;
import component_model_loader.SchoolYearML;
import daoimpl.CurriculumDaoImpl;
import daoimpl.GradeLevelDaoImpl;
import daoimpl.SchoolYearDaoImpl;
import daoimpl.SubjectDaoImpl;
import static view.CurriculumManagementContainer.getTblCreatedCurriculum;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import layout_utility.CurriculumUtility;
import model.Curriculum;
import model.GradeLevel;
import model.SchoolYear;
import model.Subject;
import validation.CurriculumValidation;

/**
 *
 * @author francisunoxx
 */
public class UpdateCurriculum extends javax.swing.JFrame {

    GradeLevelML glu = new GradeLevelML();
    SchoolYearML syu = new SchoolYearML();
    CurriculumML cu = new CurriculumML();
    
    GradeLevel gradeLevel = new GradeLevel();
    Curriculum curriculum = new Curriculum();
    Subject subject = new Subject();
    SchoolYear schoolYear = new SchoolYear();
    
    SubjectDaoImpl sdi = new SubjectDaoImpl();
    GradeLevelDaoImpl gldi = new GradeLevelDaoImpl();
    SchoolYearDaoImpl sydi = new SchoolYearDaoImpl();
    CurriculumDaoImpl cdi = new CurriculumDaoImpl();
    
    CurriculumUtility curriculumUtility = new CurriculumUtility();
    public UpdateCurriculum() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        pack();
        
        cbFilterControlGradeLevel.setModel(glu.getAllGradeLevels());
        cbFilterControlGradeLevel.setSelectedIndex(-1);
        
        cbFilterControlCurriculumName.setSelectedIndex(-1);
        
        cbCreatedGradeLevel.setModel(glu.getAllGradeLevels());
        
        cbCreatedSchoolYearStart.setModel(syu.getAllSchoolYearStart());
        
        cbCreatedSchoolYearEnd.setModel(syu.getAllSchoolYearEnd());
        
        tblCurriculumList.setModel(cu.getAllCreatedCurriculumInfo());
        
        tblCurriculumList.getColumnModel().getColumn(0).setMinWidth(0);
        tblCurriculumList.getColumnModel().getColumn(0).setMaxWidth(0);
        
        
        
//        cbCreatedSchoolYearStart.setModel(cu.getCurriculumSchoolYearStart(gradeLevel));
        
//        cbCreatedSchoolYearEnd.setModel(cu.getCurriculumSchoolYearEnd(gradeLevel));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbFilterControlGradeLevel = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbFilterControlCurriculumName = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbCreatedGradeLevel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbCreatedSchoolYearStart = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbCreatedSchoolYearEnd = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfCurriculumName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taCurriculumDescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurriculumList = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCreatedCurriculumList = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(692, 100));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel11.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Grade Level:");
        jPanel11.add(jLabel5, new java.awt.GridBagConstraints());

        cbFilterControlGradeLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFilterControlGradeLevelItemStateChanged(evt);
            }
        });
        jPanel11.add(cbFilterControlGradeLevel, new java.awt.GridBagConstraints());

        jLabel4.setText("Curriculum Name:");
        jPanel11.add(jLabel4, new java.awt.GridBagConstraints());

        cbFilterControlCurriculumName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFilterControlCurriculumNameItemStateChanged(evt);
            }
        });
        jPanel11.add(cbFilterControlCurriculumName, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        jPanel4.add(jPanel11, gridBagConstraints);

        jPanel10.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("SY:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel10.add(jLabel2, gridBagConstraints);

        cbCreatedGradeLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCreatedGradeLevelItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel10.add(cbCreatedGradeLevel, gridBagConstraints);

        jLabel1.setText("Grade Level:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel10.add(jLabel1, gridBagConstraints);

        cbCreatedSchoolYearStart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCreatedSchoolYearStartItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel10.add(cbCreatedSchoolYearStart, gridBagConstraints);

        jLabel3.setText("to");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel10.add(jLabel3, gridBagConstraints);

        cbCreatedSchoolYearEnd.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel10.add(cbCreatedSchoolYearEnd, gridBagConstraints);

        jLabel6.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel10.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel10.add(tfCurriculumName, gridBagConstraints);

        jLabel7.setText("Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel10.add(jLabel7, gridBagConstraints);

        taCurriculumDescription.setColumns(20);
        taCurriculumDescription.setRows(5);
        jScrollPane3.setViewportView(taCurriculumDescription);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel10.add(jScrollPane3, gridBagConstraints);

        jPanel4.add(jPanel10, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setPreferredSize(new java.awt.Dimension(333, 300));

        tblCurriculumList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Code", "Subject Name", "School Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCurriculumList);
        if (tblCurriculumList.getColumnModel().getColumnCount() > 0) {
            tblCurriculumList.getColumnModel().getColumn(0).setResizable(false);
            tblCurriculumList.getColumnModel().getColumn(1).setResizable(false);
            tblCurriculumList.getColumnModel().getColumn(2).setResizable(false);
            tblCurriculumList.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jPanel5, gridBagConstraints);

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setPreferredSize(new java.awt.Dimension(80, 300));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel6.add(jButton1, gridBagConstraints);

        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel6.add(jButton2, gridBagConstraints);

        jPanel3.add(jPanel6, new java.awt.GridBagConstraints());

        jPanel7.setBackground(java.awt.Color.white);
        jPanel7.setPreferredSize(new java.awt.Dimension(333, 300));

        tblCreatedCurriculumList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Code", "Subject Name", "School Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCreatedCurriculumList);
        if (tblCreatedCurriculumList.getColumnModel().getColumnCount() > 0) {
            tblCreatedCurriculumList.getColumnModel().getColumn(0).setResizable(false);
            tblCreatedCurriculumList.getColumnModel().getColumn(1).setResizable(false);
            tblCreatedCurriculumList.getColumnModel().getColumn(2).setResizable(false);
            tblCreatedCurriculumList.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        jPanel3.add(jPanel7, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Curriculum Details", jPanel2);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Actions");

        jMenuItem1.setText("Apply");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFilterControlGradeLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFilterControlGradeLevelItemStateChanged
        if(cbFilterControlGradeLevel.getSelectedIndex() > -1)
        {
            //Setter call on Curriculum
            gradeLevel.setLevel((Integer) cbFilterControlGradeLevel.getSelectedItem());
            
            //Set model on cbFilterControlCurriculumName
            cbFilterControlCurriculumName.setModel(cu.getAllCurriculumNameByGradeLevel(gradeLevel));
        }
    }//GEN-LAST:event_cbFilterControlGradeLevelItemStateChanged

    private void cbFilterControlCurriculumNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFilterControlCurriculumNameItemStateChanged
        if(cbFilterControlCurriculumName.getSelectedIndex() != -1)
        {
            //Setter call from Curriculum
            curriculum.setCurriculumTitle((String) cbFilterControlCurriculumName.getSelectedItem());
            
            //Setter call from Curriclum & Method call from CurriculumDaoImpl
            curriculum.setCurriculumId(cdi.getCurriculumId(curriculum));
            
            //Set model on cbCurriculumList & Method call from CurriculumML
            tblCurriculumList.setModel(cu.getCreatedCurriculumInfoById(curriculum));
        }
    }//GEN-LAST:event_cbFilterControlCurriculumNameItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = tblCurriculumList.getSelectedRow(); //selected row whic has the data to be added
        Object selectedSubjCode = tblCurriculumList.getValueAt(selectedRow, 1);
        //        JOptionPane.showMessageDialog(null, selectedSubjCode);

        int rows = tblCreatedCurriculumList.getRowCount();
        Object[] curriculumSubjects = new Object[rows];

        for (int j = 0; j < rows; j++) {
            curriculumSubjects[j] = tblCreatedCurriculumList.getValueAt(j, 1);
        }

        if (Arrays.asList(curriculumSubjects).contains(selectedSubjCode)) {
            JOptionPane.showMessageDialog(null, selectedSubjCode + " is already on the list.");
        } else {
            DefaultTableModel curriculumSubjectsModel = (DefaultTableModel) tblCreatedCurriculumList.getModel();

            Object[] rowData = new Object[tblCurriculumList.getColumnCount()];
            int selectedRowIndex = tblCurriculumList.getSelectedRow();
            for (int i = 0; i < tblCurriculumList.getColumnCount(); i++) {
                rowData[i] = tblCurriculumList.getValueAt(selectedRowIndex, i);
            }
            curriculumSubjectsModel.addRow(rowData);
            tblCreatedCurriculumList.setModel(curriculumSubjectsModel);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tblCreatedCurriculumList.getSelectedRow() > -1) {
            int selectedRowIndex = tblCreatedCurriculumList.getSelectedRow();
            DefaultTableModel curriculumSubjectsModel = (DefaultTableModel) tblCreatedCurriculumList.getModel();
            curriculumSubjectsModel.removeRow(selectedRowIndex);
            tblCreatedCurriculumList.clearSelection();
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbCreatedSchoolYearStartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCreatedSchoolYearStartItemStateChanged
        int selectedYearFrom = cbCreatedSchoolYearStart.getSelectedIndex();
        cbCreatedSchoolYearEnd.setSelectedIndex(selectedYearFrom);
            
        //Setter call from SchoolYear
        schoolYear.setSchoolYearId(sydi.getId((int) cbCreatedSchoolYearStart.getSelectedItem()));
    }//GEN-LAST:event_cbCreatedSchoolYearStartItemStateChanged

    private void cbCreatedGradeLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCreatedGradeLevelItemStateChanged

        gradeLevel.setLevel((Integer) cbCreatedGradeLevel.getSelectedItem());

    }//GEN-LAST:event_cbCreatedGradeLevelItemStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Setter call from CurriculumDaoImpl
        curriculum.setCurriculumId((int) getTblCreatedCurriculum().getValueAt(getTblCreatedCurriculum().getSelectedRow(), 0));
        
        List list = new ArrayList();
        list.add(cbCreatedGradeLevel.getSelectedItem());
        list.add(cbCreatedSchoolYearStart.getSelectedItem() + "-" + cbCreatedSchoolYearEnd.getSelectedItem());
        list.add(tfCurriculumName.getText());
        list.add(taCurriculumDescription.getText());
        
        for(int i = 0; i < tblCreatedCurriculumList.getModel().getRowCount(); i++)
        {
            list.add(tblCreatedCurriculumList.getValueAt(i, 1));
            list.add(tblCreatedCurriculumList.getValueAt(i, 2));
        }
        
        
        
        list.retainAll(new CurriculumValidation().checkCurriculumChanges(curriculum));
        
        //If nothing changes
        if(list.size() == 6)
        {
            JOptionPane.showMessageDialog(null, "No changes detected");
        }
        //If anything changes
        else
        {
            //Setter call from Curriculum
            //Get id from getTblCreatedCurriculum()
            curriculum.setCurriculumId((int) getTblCreatedCurriculum().getValueAt(getTblCreatedCurriculum().getSelectedRow(), 0));

            //Method call from CurriculumDaoImpl
            cdi.deleteCreatedCurriculumById(curriculum);

            //while looping to row count of table
            for(int i = 0; i < tblCreatedCurriculumList.getRowCount(); i++)
            {

                //Setter call from Subject
                subject.setSubjectTitle((String) tblCreatedCurriculumList.getValueAt(i, 2));
                //Setter call from Subject & Method call from SubjectDaoImpl
                subject.setSubjectId(sdi.getSubjectId(subject));

                //Setter call from GradeLevel & Getting cbGradeLevel id
                gradeLevel.setId(gldi.getId(gradeLevel));

                //Setter call from SchoolYear
                schoolYear.setSchoolYearId(schoolYear.getSchoolYearId());

                //Setter call from Curriculum while getting the text of jtextfield and jtextarea
                curriculum.setCurriculumTitle(tfCurriculumName.getText());
                curriculum.setCurriculumDescription(taCurriculumDescription.getText());

                //Method call from CurriculumDaoImpl
                cdi.updateCreatedCurriculumById(curriculum, gradeLevel, schoolYear, subject);
            }

            JOptionPane.showMessageDialog(null, "Successfully updating curriculum "+tfCurriculumName.getText());
        }
        
        


    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    public JTable getTblCreatedCurriculumList()
    {
        return tblCreatedCurriculumList;
    }
    
    public JComboBox getCbCreatedGradeLevel()
    {
        return cbCreatedGradeLevel;
    }
    
    public JComboBox getCbCreatedSchoolYearStart()
    {
        return cbCreatedSchoolYearStart;
    }
    
    public JComboBox getCbCreatedSchoolYearEnd()
    {
        return cbCreatedSchoolYearEnd;
    }
    
    public JTextField getTfCurriculumName()
    {
        return tfCurriculumName;
    }
    
    public JTextArea getTaCurriculumDescription()
    {
        return taCurriculumDescription;
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCreatedGradeLevel;
    private javax.swing.JComboBox<String> cbCreatedSchoolYearEnd;
    private javax.swing.JComboBox<String> cbCreatedSchoolYearStart;
    private javax.swing.JComboBox<String> cbFilterControlCurriculumName;
    private javax.swing.JComboBox<String> cbFilterControlGradeLevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea taCurriculumDescription;
    private javax.swing.JTable tblCreatedCurriculumList;
    private javax.swing.JTable tblCurriculumList;
    private javax.swing.JTextField tfCurriculumName;
    // End of variables declaration//GEN-END:variables
}
